### ISSUE TITLE
Caching by branch

### ISSUE THREAD

**Issue by Francesco-Borzi** [NiklasPor/nx-remotecache-azure#24]
I've noticed that if you make big changes in a branch, cache them, then open a separate new branch from main and make other big changes and cache them, you lose the first cache.

Is there a way to cache the result not only per NX library but per branch AND library?

**Comment by ontoneio** [comment]
@Francesco-Borzi I am curious about your use case, because my understanding is that NX caches are kind of ephemeral in nature and that your own input an output settings on the targets themselves have more to do with the invalidation of a cache then not. There are CLI commands like `run-many` and `affected` that both take `--base` and `--head` parameters but that is only to calculate between commits I think.

NX Caches are only tracking whether there was a change or not, so I can't think off top how one would achieve this from an nx standpoint.

**Comment by NiklasPor** [comment]
Nx caches are always based on the state of the repository (and environment). You can configure it on your own, this is rather a question regarding NX caching and general and not specific to this package.

You can read more on what modifies the caching usage here: https://nx.dev/concepts/how-caching-works#define-cache-inputs
